name = "Chess"
style = "Chess"
board_size = [8, 8]
player_names = ["White", "Black"]

[piece_types.Pawn]
symbol = "P"
moves = [
  "forward_one_no_capture",
  "first_forward_two_no_capture",
  "en_passant", 
  "diagonal_capture"
]
promotion = ["Queen", "Rook", "Bishop", "Knight"]

[piece_types.Knight]
symbol = "N"
moves = ["orthogonal_one_diagonal_one_jump"]

[piece_types.Bishop]
symbol = "B"
moves = ["diagonal"]

[piece_types.Rook]
symbol = "R"
moves = ["orthogonal"]

[piece_types.Queen]
symbol = "Q"
moves = ["any_direction"]

[piece_types.King]
symbol = "K"
moves = ["adjacent"]

[starting_position]
"0,0" = "wR"
"0,1" = "wN"
"0,2" = "wB"
"0,3" = "wQ"
"0,4" = "wK"
"0,5" = "wB"
"0,6" = "wN"
"0,7" = "wR"
"1,0" = "wP"
"1,1" = "wP"
"1,2" = "wP"
"1,3" = "wP"
"1,4" = "wP"
"1,5" = "wP"
"1,6" = "wP"
"1,7" = "wP"
"6,0" = "bP"
"6,1" = "bP"
"6,2" = "bP"
"6,3" = "bP"
"6,4" = "bP"
"6,5" = "bP"
"6,6" = "bP"
"6,7" = "bP"
"7,0" = "bR"
"7,1" = "bN"
"7,2" = "bB"
"7,3" = "bQ"
"7,4" = "bK"
"7,5" = "bB"
"7,6" = "bN"
"7,7" = "bR"
