name = "Chu Shogi"
style = "Shogi"
board_size = [12, 12]
player_names = ["Black", "White"]

[piece_types.Pawn]
symbol = "P"
moves = ["forward_one"]
promotion = ["Tokin"]

[piece_types.GoBetween]
symbol = "GB"
moves = ["forward_one", "backward_one"]
promotion = ["DrunkElephant"]

[piece_types.SideMover]
symbol = "SM"
moves = ["horizontal", "forward_one", "backward_one"]
promotion = ["FreeBoar"]

[piece_types.VerticalMover]
symbol = "VM"
moves = ["vertical", "left_one", "right_one"]
promotion = ["FlyingOx"]

[piece_types.Bishop]
symbol = "B"
moves = ["diagonal"]
promotion = ["DragonHorse"]

[piece_types.Rook]
symbol = "R"
moves = ["orthogonal"]
promotion = ["DragonKing"]

[piece_types.DragonHorse]
symbol = "DH"
moves = ["diagonal", "adjacent"]
promotion = ["HornedFalcon"]

[piece_types.DragonKing]
symbol = "DK"
moves = ["straight", "adjacent"]
promotion = ["SoaringEagle"]

[piece_types.Lance]
symbol = "L"
moves = ["forward_unlimited"]
promotion = ["WhiteHorse"]

[piece_types.ReverseChariot]
symbol = "RC"
moves = ["vertical"]
promotion = ["Whale"]

[piece_types.BlindTiger]
symbol = "BT"
moves = ["diagonal_one", "backward_one", "horizontal_one"]
promotion = ["FlyingStag"]

[piece_types.FerociousLeopard]
symbol = "FL"
moves = ["diagonal_one", "vertical_one"]
promotion = ["Bishop"]

[piece_types.Copper]
symbol = "C"
moves = ["vertical_one", "diagonal_forward_one"]
promotion = ["SideMover"]

[piece_types.Silver]
symbol = "S"
moves = ["diagonal_one", "forward_one"]
promotion = ["VerticalMover"]

[piece_types.Gold]
symbol = "G"
moves = ["straight_one", "diagonal_forward_one"]
promotion = ["Rook"]

[piece_types.DrunkElephant]
symbol = "DE"
moves = ["diagonal_one", "forward_one", "horizontal_one"]
promotion = ["CrownPrince"]

[piece_types.Kirin]
symbol = "Ki"
moves = ["diagonal_one", "orthogonal_jump_one"]
promotion = ["Lion"]

[piece_types.Phoenix]
symbol = "Ph"
moves = ["orthogonal_one", "diagonal_jump_one"]
promotion = ["Lion"]

[piece_types.FreeKing]
symbol = "FK"
moves = ["diagonal", "orthogonal"]

[piece_types.Lion]
symbol = "Ln"
moves = ["step_twice_with_jumping"]

[piece_types.CrownPrince]
symbol = "CP"
moves = ["adjacent"]

[piece_types.King]
symbol = "K"
moves = ["adjacent"]

[piece_types.Tokin]
symbol = "T"
moves = ["straight_one", "diagonal_forward_one"]

[piece_types.FlyingStag]
symbol = "FS"
moves = ["vertical", "diagonal_one", "horizontal_one"]

[piece_types.FlyingOx]
symbol = "FS"
moves = ["vertical", "diagonal"]

[piece_types.FlyingBoar]
symbol = "FB"
moves = ["horizontal", "diagonal"]

[piece_types.Whale]
symbol = "Wh"
moves = ["vertical", "diagonal_backward"]

[piece_types.WhiteHorse]
symbol = "WH"
moves = ["vertical", "diagonal_forward"]

[piece_types.HornedFalcon]
symbol = "HF"
moves = ["step_or_jump_forward", "igui_forward", "jitto_forward"]

[piece_types.SoaringEagle]
symbol = "SE"
moves = ["step_or_jump_diagonal_forward", "igui_diagonal_forward", "jitto_diagonal_forward"]


[starting_position]
"0,0" = "bL"
"0,1" = "bFL"
"0,2" = "bC"
"0,3" = "bS"
"0,4" = "bG"
"0,5" = "bK"
"0,6" = "bDE"
"0,7" = "bG"
"0,8" = "bS"
"0,9" = "bC"
"0,10" = "bFL"
"0,11" = "bL"
"1,0" = "bRC"
"1,2" = "bB"
"1,4" = "bBT"
"1,5" = "bKi"
"1,6" = "bPh"
"1,7" = "bBT"
"1,9" = "bB"
"1,11" = "bRC"
"2,0" = "bSM"
"2,1" = "bVM"
"2,2" = "bR"
"2,3" = "bDH"
"2,4" = "bDK"
"2,5" = "bLn"
"2,6" = "bFK"
"2,7" = "bDK"
"2,8" = "bDH"
"2,9" = "bR"
"2,10" = "bVM"
"2,11" = "bSM"
"3,0" = "bP"
"3,1" = "bP"
"3,2" = "bP"
"3,3" = "bP"
"3,4" = "bP"
"3,5" = "bP"
"3,6" = "bP"
"3,7" = "bP"
"3,8" = "bP"
"3,9" = "bP"
"3,10" = "bP"
"3,11" = "bP"
"4,3" = "bGB"
"4,8" = "bGB"
"7,3" = "wGB"
"7,8" = "wGB"
"8,0" = "wP"
"8,1" = "wP"
"8,2" = "wP"
"8,3" = "wP"
"8,4" = "wP"
"8,5" = "wP"
"8,6" = "wP"
"8,7" = "wP"
"8,8" = "wP"
"8,9" = "wP"
"8,10" = "wP"
"8,11" = "wP"
"9,0" = "wSM"
"9,1" = "wVM"
"9,2" = "wR"
"9,3" = "wDH"
"9,4" = "wDK"
"9,5" = "wFK"
"9,6" = "wLn"
"9,7" = "wDK"
"9,8" = "wDH"
"9,9" = "wR"
"9,10" = "wVM"
"9,11" = "wSM"
"10,0" = "wRC"
"10,2" = "wB"
"10,4" = "wBT"
"10,5" = "wPh"
"10,6" = "wKi"
"10,7" = "wBT"
"10,9" = "wB"
"10,11" = "wRC"
"11,0" = "wL"
"11,1" = "wFL"
"11,2" = "wC"
"11,3" = "wS"
"11,4" = "wG"
"11,5" = "wDE"
"11,6" = "wK"
"11,7" = "wG"
"11,8" = "wS"
"11,9" = "wC"
"11,10" = "wFL"
"11,11" = "wL"
