name = "Shogi"
style = "Shogi"
board_size = [9, 9]
player_names = ["Black", "White"]

[piece_types.Pawn]
symbol = "P"
moves = ["forward_one"]
promotion = ["PromotedPawn"]

[piece_types.Lance]
symbol = "L"
moves = ["forward_unlimited"]
promotion = ["PromotedLance"]

[piece_types.Knight]
symbol = "N"
moves = ["forward_one_diagonal_one_jump"]
promotion = ["PromotedKnight"]
force_promotion = ["back_two_ranks"]

[piece_types.Silver]
symbol = "S"
moves = ["diagonal_one", "forward_one"]
promotion = ["PromotedSilver"]

[piece_types.Gold]
symbol = "G"
moves = ["orthogonal_one", "diagonal_forward_one"]

[piece_types.Bishop]
symbol = "B"
moves = ["diagonal"]
promotion = ["Horse"]

[piece_types.Rook]
symbol = "R"
moves = ["orthogonal"]
promotion = ["Dragon"]

[piece_types.PromotedPawn]
symbol = "+P"
name = "Tokin"
moves = ["orthogonal_one", "diagonal_forward_one"]

[piece_types.PromotedLance]
symbol = "+L"
name = "Tokin"
moves = ["orthogonal_one", "diagonal_forward_one"]

[piece_types.PromotedKnight]
symbol = "+N"
name = "Tokin"
moves = ["orthogonal_one", "diagonal_forward_one"]

[piece_types.PromotedSilver]
symbol = "+S"
name = "Tokin"
moves = ["orthogonal_one", "diagonal_forward_one"]

[piece_types.Horse]
symbol = "+B"
moves = ["diagonal", "orthogonal_one"]

[piece_types.Dragon]
symbol = "+R"
moves = ["orthogonal", "diagonal_one"]

[piece_types.King]
symbol = "K"
moves = ["adjacent"]

[starting_position]
"0,0" = "bL"
"0,1" = "bN"
"0,2" = "bS"
"0,3" = "bG"
"0,4" = "bK"
"0,5" = "bG"
"0,6" = "bS"
"0,7" = "bN"
"0,8" = "bL"
"1,1" = "bB"
"1,7" = "bR"
"2,0" = "bP"
"2,1" = "bP"
"2,2" = "bP"
"2,3" = "bP"
"2,4" = "bP"
"2,5" = "bP"
"2,6" = "bP"
"2,7" = "bP"
"2,8" = "bP"
"6,0" = "wP"
"6,1" = "wP"
"6,2" = "wP"
"6,3" = "wP"
"6,4" = "wP"
"6,5" = "wP"
"6,6" = "wP"
"6,7" = "wP"
"6,8" = "wP"
"7,1" = "wR"
"7,7" = "wB"
"8,0" = "wL"
"8,1" = "wN"
"8,2" = "wS"
"8,3" = "wG"
"8,4" = "wK"
"8,5" = "wG"
"8,6" = "wS"
"8,7" = "wN"
"8,8" = "wL"
